  # 'jekyll serve'. If you change this file, please restart the server process.
  
  # Site settings
 -title: helloooo
 +title: Clara Pak
  email: pak.clara@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  baseurl: "" # the subpath of your site, e.g. /blog
 -url: "http://yourdomain.com" # the base hostname & protocol for your site
 -twitter_username: jekyllrb
 -github_username:  jekyll
 +url: "http://clarapak.me" # the base hostname & protocol for your site
 +twitter_username: clarampak
 +github_username:  clarapak
  
  # Build settings
  markdown: kramdown
